package com.gcit.lms.entities;

// Generated Jan 30, 2014 2:32:50 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblAuthor generated by hbm2java
 */
@Entity
@Table(name = "tbl_author", catalog = "library")
public class Author implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7714336221560384376L;
	private Integer authorId;
	private String authorName;
	private Set<Book> tblBooks = new HashSet<Book>(0);

	public Author() {
	}

	public Author(String authorName) {
		this.authorName = authorName;
	}

	public Author(String authorName, Set<Book> tblBooks) {
		this.authorName = authorName;
		this.tblBooks = tblBooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "authorId", unique = true, nullable = false)
	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	@Column(name = "authorName", nullable = false, length = 45)
	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
	public Set<Book> getTblBooks() {
		return this.tblBooks;
	}

	public void setTblBooks(Set<Book> tblBooks) {
		this.tblBooks = tblBooks;
	}

}
