package com.gcit.lms.entities;

// Generated Jan 30, 2014 2:32:50 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblBook generated by hbm2java
 */
@Entity
@Table(name = "tbl_book", catalog = "library")
public class Book implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4148682649258410925L;
	private Integer bookId;
	private Author author;
	private Publisher publisher;
	private String title;
	private Set<BookLoans> bookLoans = new HashSet<BookLoans>(0);
	private Set<BookCopies> bookCopies = new HashSet<BookCopies>(0);

	public Book() {
	}

	public Book(String title) {
		this.title = title;
	}

	public Book(Author author, Publisher publisher,
			String title, Set<BookLoans> bookLoans,
			Set<BookCopies> bookCopies) {
		this.author = author;
		this.publisher = publisher;
		this.title = title;
		this.bookLoans = bookLoans;
		this.bookCopies = bookCopies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bookId", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "authId")
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pubId")
	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookLoans> getBookLoans() {
		return this.bookLoans;
	}

	public void setBookLoans(Set<BookLoans> bookLoans) {
		this.bookLoans = bookLoans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<BookCopies> getBookCopies() {
		return this.bookCopies;
	}

	public void setBookCopies(Set<BookCopies> bookCopies) {
		this.bookCopies = bookCopies;
	}

}
