package com.gcit.lms.entities;

// Generated Jan 30, 2014 2:32:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblBookCopiesId generated by hbm2java
 */
@Embeddable
public class BookCopiesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 894427227008896593L;
	private int bookId;
	private int branchId;

	public BookCopiesId() {
	}

	public BookCopiesId(int bookId, int branchId) {
		this.bookId = bookId;
		this.branchId = branchId;
	}

	@Column(name = "bookId", nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "branchId", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookCopiesId))
			return false;
		BookCopiesId castOther = (BookCopiesId) other;

		return (this.getBookId() == castOther.getBookId())
				&& (this.getBranchId() == castOther.getBranchId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + this.getBranchId();
		return result;
	}

}
