package com.gcit.lms.entities;

// Generated Jan 30, 2014 2:32:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblBookLoansId generated by hbm2java
 */
@Embeddable
public class BookLoansId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8247068975208871286L;
	private int bookId;
	private int branchId;
	private int cardNo;

	public BookLoansId() {
	}

	public BookLoansId(int bookId, int branchId, int cardNo) {
		this.bookId = bookId;
		this.branchId = branchId;
		this.cardNo = cardNo;
	}

	@Column(name = "bookId", nullable = false)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "branchId", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "cardNo", nullable = false)
	public int getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(int cardNo) {
		this.cardNo = cardNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookLoansId))
			return false;
		BookLoansId castOther = (BookLoansId) other;

		return (this.getBookId() == castOther.getBookId())
				&& (this.getBranchId() == castOther.getBranchId())
				&& (this.getCardNo() == castOther.getCardNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + this.getBranchId();
		result = 37 * result + this.getCardNo();
		return result;
	}

}
