package com.gcit.lms.entities;

// Generated Jan 30, 2014 2:32:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBookLoans generated by hbm2java
 */
@Entity
@Table(name = "tbl_book_loans", catalog = "library")
public class BookLoans implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1247356709366439265L;
	private BookLoansId id;
	private Borrower borrower;
	private LibraryBranch libraryBranch;
	private Book book;
	private Date dateOut;
	private Date dueDate;

	public BookLoans() {
	}

	public BookLoans(BookLoansId id, Borrower tblBorrower,
			LibraryBranch tblLibraryBranch, Book tblBook) {
		this.id = id;
		this.borrower = tblBorrower;
		this.libraryBranch = tblLibraryBranch;
		this.book = tblBook;
	}

	public BookLoans(BookLoansId id, Borrower tblBorrower,
			LibraryBranch tblLibraryBranch, Book tblBook, Date dateOut,
			Date dueDate) {
		this.id = id;
		this.borrower = tblBorrower;
		this.libraryBranch = tblLibraryBranch;
		this.book = tblBook;
		this.dateOut = dateOut;
		this.dueDate = dueDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookId", column = @Column(name = "bookId", nullable = false)),
			@AttributeOverride(name = "branchId", column = @Column(name = "branchId", nullable = false)),
			@AttributeOverride(name = "cardNo", column = @Column(name = "cardNo", nullable = false)) })
	public BookLoansId getId() {
		return this.id;
	}

	public void setId(BookLoansId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cardNo", nullable = false, insertable = false, updatable = false)
	public Borrower getBorrower() {
		return this.borrower;
	}

	public void setBorrower(Borrower tblBorrower) {
		this.borrower = tblBorrower;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchId", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getLibraryBranch() {
		return this.libraryBranch;
	}

	public void setLibraryBranch(LibraryBranch tblLibraryBranch) {
		this.libraryBranch = tblLibraryBranch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookId", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book tblBook) {
		this.book = tblBook;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateOut", length = 19)
	public Date getDateOut() {
		return this.dateOut;
	}

	public void setDateOut(Date dateOut) {
		this.dateOut = dateOut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dueDate", length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

}
