package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblBook generated by hbm2java
 */
@Entity
@Table(name = "tbl_book", catalog = "library")
public class Book implements java.io.Serializable {

	private Integer catId;
	private Catalog catalog;
	private Author author;
	private Publisher publisher;
	private String title;

	public Book() {
	}

	public Book(Catalog catalog, String title) {
		this.catalog = catalog;
		this.title = title;
	}

	public Book(Catalog catalog, Author author,
			Publisher publisher, String title) {
		this.catalog = catalog;
		this.author = author;
		this.publisher = publisher;
		this.title = title;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tblCatalog"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "catId", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Catalog getTblCatalog() {
		return this.catalog;
	}

	public void setTblCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "authId")
	public Author getTblAuthor() {
		return this.author;
	}

	public void setTblAuthor(Author author) {
		this.author = author;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pubId")
	public Publisher getTblPublisher() {
		return this.publisher;
	}

	public void setTblPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
