package com.gcit.lms.entities;

// Generated Jan 30, 2014 2:32:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblBookCopies generated by hbm2java
 */
@Entity
@Table(name = "tbl_book_copies", catalog = "library")
public class BookCopies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2399868278926867056L;
	private BookCopiesId id;
	private LibraryBranch libraryBranch;
	private Book book;
	private Integer noOfCopies;

	public BookCopies() {
	}

	public BookCopies(BookCopiesId id, LibraryBranch libraryBranch,
			Book book) {
		this.id = id;
		this.libraryBranch = libraryBranch;
		this.book = book;
	}

	public BookCopies(BookCopiesId id, LibraryBranch libraryBranch,
			Book book, Integer noOfCopies) {
		this.id = id;
		this.libraryBranch = libraryBranch;
		this.book = book;
		this.noOfCopies = noOfCopies;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookId", column = @Column(name = "bookId", nullable = false)),
			@AttributeOverride(name = "branchId", column = @Column(name = "branchId", nullable = false)) })
	public BookCopiesId getId() {
		return this.id;
	}

	public void setId(BookCopiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchId", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getlibraryBranch() {
		return this.libraryBranch;
	}

	public void setLibraryBranch(LibraryBranch libraryBranch) {
		this.libraryBranch = libraryBranch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookId", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@Column(name = "noOfCopies")
	public Integer getNoOfCopies() {
		return this.noOfCopies;
	}

	public void setNoOfCopies(Integer noOfCopies) {
		this.noOfCopies = noOfCopies;
	}

}
