package com.gcit.lms.entities;

// Generated Jan 30, 2014 2:32:50 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblBorrower generated by hbm2java
 */
@Entity
@Table(name = "tbl_borrower", catalog = "library")
public class Borrower implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7073891534395561905L;
	private Integer cardNo;
	private String name;
	private String address;
	private String phone;
	private Set<BookLoans> tblBookLoanses = new HashSet<BookLoans>(0);

	public Borrower() {
	}

	public Borrower(String name, String address, String phone,
			Set<BookLoans> tblBookLoanses) {
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.tblBookLoanses = tblBookLoanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cardNo", unique = true, nullable = false)
	public Integer getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(Integer cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "borrower")
	public Set<BookLoans> getTblBookLoanses() {
		return this.tblBookLoanses;
	}

	public void setTblBookLoanses(Set<BookLoans> tblBookLoanses) {
		this.tblBookLoanses = tblBookLoanses;
	}

}
