package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TblCatalog generated by hbm2java
 */
@Entity
@Table(name = "tbl_catalog", catalog = "library")
public class Catalog implements java.io.Serializable {

	private Integer catId;
	private String itemType;
	private Set<ItemLoans> tblItemLoanses = new HashSet<ItemLoans>(0);
	private Book book;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);
	private Set<ItemCopies> tblItemCopieses = new HashSet<ItemCopies>(0);

	public Catalog() {
	}

	public Catalog(String itemType) {
		this.itemType = itemType;
	}

	public Catalog(String itemType, Set<ItemLoans> tblItemLoanses,
			Book book, Set<Reservation> reservations,
			Set<ItemCopies> tblItemCopieses) {
		this.itemType = itemType;
		this.tblItemLoanses = tblItemLoanses;
		this.book = book;
		this.reservations = reservations;
		this.tblItemCopieses = tblItemCopieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "catId", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "itemType", nullable = false, length = 45)
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCatalog")
	public Set<ItemLoans> getTblItemLoanses() {
		return this.tblItemLoanses;
	}

	public void setTblItemLoanses(Set<ItemLoans> tblItemLoanses) {
		this.tblItemLoanses = tblItemLoanses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tblCatalog")
	public Book getTblBook() {
		return this.book;
	}

	public void setTblBook(Book book) {
		this.book = book;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCatalog")
	public Set<Reservation> getTblReservations() {
		return this.reservations;
	}

	public void setTblReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCatalog")
	public Set<ItemCopies> getTblItemCopieses() {
		return this.tblItemCopieses;
	}

	public void setTblItemCopieses(Set<ItemCopies> tblItemCopieses) {
		this.tblItemCopieses = tblItemCopieses;
	}

}
