package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblItemCopies generated by hbm2java
 */
@Entity
@Table(name = "tbl_item_copies", catalog = "library")
public class ItemCopies implements java.io.Serializable {

	private ItemCopiesId id;
	private Catalog catalog;
	private LibraryBranch libraryBranch;
	private int noOfCopies;
	private int copiesAvailable;

	public ItemCopies() {
	}

	public ItemCopies(ItemCopiesId id, Catalog catalog,
			LibraryBranch libraryBranch, int noOfCopies,
			int copiesAvailable) {
		this.id = id;
		this.catalog = catalog;
		this.libraryBranch = libraryBranch;
		this.noOfCopies = noOfCopies;
		this.copiesAvailable = copiesAvailable;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "catId", column = @Column(name = "catId", nullable = false)),
			@AttributeOverride(name = "branchId", column = @Column(name = "branchId", nullable = false)) })
	public ItemCopiesId getId() {
		return this.id;
	}

	public void setId(ItemCopiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catId", nullable = false, insertable = false, updatable = false)
	public Catalog getTblCatalog() {
		return this.catalog;
	}

	public void setTblCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchId", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getTblLibraryBranch() {
		return this.libraryBranch;
	}

	public void setTblLibraryBranch(LibraryBranch libraryBranch) {
		this.libraryBranch = libraryBranch;
	}

	@Column(name = "noOfCopies", nullable = false)
	public int getNoOfCopies() {
		return this.noOfCopies;
	}

	public void setNoOfCopies(int noOfCopies) {
		this.noOfCopies = noOfCopies;
	}

	@Column(name = "copiesAvailable", nullable = false)
	public int getCopiesAvailable() {
		return this.copiesAvailable;
	}

	public void setCopiesAvailable(int copiesAvailable) {
		this.copiesAvailable = copiesAvailable;
	}

}
