package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblItemCopiesId generated by hbm2java
 */
@Embeddable
public class ItemCopiesId implements java.io.Serializable {

	private int catId;
	private int branchId;

	public ItemCopiesId() {
	}

	public ItemCopiesId(int catId, int branchId) {
		this.catId = catId;
		this.branchId = branchId;
	}

	@Column(name = "catId", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Column(name = "branchId", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemCopiesId))
			return false;
		ItemCopiesId castOther = (ItemCopiesId) other;

		return (this.getCatId() == castOther.getCatId())
				&& (this.getBranchId() == castOther.getBranchId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCatId();
		result = 37 * result + this.getBranchId();
		return result;
	}

}
