package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblItemLoans generated by hbm2java
 */
@Entity
@Table(name = "tbl_item_loans", catalog = "library")
public class ItemLoans implements java.io.Serializable {

	private ItemLoansId id;
	private Catalog catalog;
	private LibraryBranch libraryBranch;
	private Date dateOut;
	private Date dueDate;
	private int renewTimes;

	public ItemLoans() {
	}

	public ItemLoans(ItemLoansId id, Catalog catalog,
			LibraryBranch libraryBranch, Date dateOut, Date dueDate,
			int renewTimes) {
		this.id = id;
		this.catalog = catalog;
		this.libraryBranch = libraryBranch;
		this.dateOut = dateOut;
		this.dueDate = dueDate;
		this.renewTimes = renewTimes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "catId", column = @Column(name = "catId", nullable = false)),
			@AttributeOverride(name = "branchId", column = @Column(name = "branchId", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "userId", nullable = false)) })
	public ItemLoansId getId() {
		return this.id;
	}

	public void setId(ItemLoansId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catId", nullable = false, insertable = false, updatable = false)
	public Catalog getTblCatalog() {
		return this.catalog;
	}

	public void setTblCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchId", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getTblLibraryBranch() {
		return this.libraryBranch;
	}

	public void setTblLibraryBranch(LibraryBranch libraryBranch) {
		this.libraryBranch = libraryBranch;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateOut", nullable = false, length = 10)
	public Date getDateOut() {
		return this.dateOut;
	}

	public void setDateOut(Date dateOut) {
		this.dateOut = dateOut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dueDate", nullable = false, length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "renewTimes", nullable = false)
	public int getRenewTimes() {
		return this.renewTimes;
	}

	public void setRenewTimes(int renewTimes) {
		this.renewTimes = renewTimes;
	}

}
