package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblItemLoansId generated by hbm2java
 */
@Embeddable
public class ItemLoansId implements java.io.Serializable {

	private int catId;
	private int branchId;
	private int userId;

	public ItemLoansId() {
	}

	public ItemLoansId(int catId, int branchId, int userId) {
		this.catId = catId;
		this.branchId = branchId;
		this.userId = userId;
	}

	@Column(name = "catId", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	@Column(name = "branchId", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemLoansId))
			return false;
		ItemLoansId castOther = (ItemLoansId) other;

		return (this.getCatId() == castOther.getCatId())
				&& (this.getBranchId() == castOther.getBranchId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCatId();
		result = 37 * result + this.getBranchId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
