package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TblLibrarian generated by hbm2java
 */
@Entity
@Table(name = "tbl_librarian", catalog = "library")
public class Librarian implements java.io.Serializable {

	private int userId;
	private User user;
	private LibraryBranch libraryBranch;

	public Librarian() {
	}

	public Librarian(User user) {
		this.user = user;
	}

	public Librarian(User user, LibraryBranch libraryBranch) {
		this.user = user;
		this.libraryBranch = libraryBranch;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "tblUser"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getTblUser() {
		return this.user;
	}

	public void setTblUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchId")
	public LibraryBranch getTblLibraryBranch() {
		return this.libraryBranch;
	}

	public void setTblLibraryBranch(LibraryBranch libraryBranch) {
		this.libraryBranch = libraryBranch;
	}

}
