package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblLibraryBranch generated by hbm2java
 */
@Entity
@Table(name = "tbl_library_branch", catalog = "library")
public class LibraryBranch implements java.io.Serializable {

	private Integer branchId;
	private String branchName;
	private String branchAddress;
	private Set<Transfers> tblTransfersesForFromBranchId = new HashSet<Transfers>(
			0);
	private Set<Librarian> librarians = new HashSet<Librarian>(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);
	private Set<Transfers> tblTransfersesForToBranchId = new HashSet<Transfers>(
			0);
	private Set<ItemCopies> tblItemCopieses = new HashSet<ItemCopies>(0);
	private Set<ItemLoans> tblItemLoanses = new HashSet<ItemLoans>(0);

	public LibraryBranch() {
	}

	public LibraryBranch(String branchName, String branchAddress) {
		this.branchName = branchName;
		this.branchAddress = branchAddress;
	}

	public LibraryBranch(String branchName, String branchAddress,
			Set<Transfers> tblTransfersesForFromBranchId,
			Set<Librarian> librarians,
			Set<Reservation> reservations,
			Set<Transfers> tblTransfersesForToBranchId,
			Set<ItemCopies> tblItemCopieses, Set<ItemLoans> tblItemLoanses) {
		this.branchName = branchName;
		this.branchAddress = branchAddress;
		this.tblTransfersesForFromBranchId = tblTransfersesForFromBranchId;
		this.librarians = librarians;
		this.reservations = reservations;
		this.tblTransfersesForToBranchId = tblTransfersesForToBranchId;
		this.tblItemCopieses = tblItemCopieses;
		this.tblItemLoanses = tblItemLoanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "branchId", unique = true, nullable = false)
	public Integer getBranchId() {
		return this.branchId;
	}

	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	@Column(name = "branchName", nullable = false, length = 45)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "branchAddress", nullable = false, length = 45)
	public String getBranchAddress() {
		return this.branchAddress;
	}

	public void setBranchAddress(String branchAddress) {
		this.branchAddress = branchAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranchByFromBranchId")
	public Set<Transfers> getTblTransfersesForFromBranchId() {
		return this.tblTransfersesForFromBranchId;
	}

	public void setTblTransfersesForFromBranchId(
			Set<Transfers> tblTransfersesForFromBranchId) {
		this.tblTransfersesForFromBranchId = tblTransfersesForFromBranchId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<Librarian> getTblLibrarians() {
		return this.librarians;
	}

	public void setTblLibrarians(Set<Librarian> librarians) {
		this.librarians = librarians;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<Reservation> getTblReservations() {
		return this.reservations;
	}

	public void setTblReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranchByToBranchId")
	public Set<Transfers> getTblTransfersesForToBranchId() {
		return this.tblTransfersesForToBranchId;
	}

	public void setTblTransfersesForToBranchId(
			Set<Transfers> tblTransfersesForToBranchId) {
		this.tblTransfersesForToBranchId = tblTransfersesForToBranchId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<ItemCopies> getTblItemCopieses() {
		return this.tblItemCopieses;
	}

	public void setTblItemCopieses(Set<ItemCopies> tblItemCopieses) {
		this.tblItemCopieses = tblItemCopieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblLibraryBranch")
	public Set<ItemLoans> getTblItemLoanses() {
		return this.tblItemLoanses;
	}

	public void setTblItemLoanses(Set<ItemLoans> tblItemLoanses) {
		this.tblItemLoanses = tblItemLoanses;
	}

}
