package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TblReservation generated by hbm2java
 */
@Entity
@Table(name = "tbl reservation", catalog = "library", uniqueConstraints = @UniqueConstraint(columnNames = "orderId"))
public class Reservation implements java.io.Serializable {

	private ReservationId id;
	private Catalog catalog;
	private User user;
	private LibraryBranch libraryBranch;
	private int orderId;

	public Reservation() {
	}

	public Reservation(ReservationId id, Catalog catalog,
			User user, LibraryBranch libraryBranch, int orderId) {
		this.id = id;
		this.catalog = catalog;
		this.user = user;
		this.libraryBranch = libraryBranch;
		this.orderId = orderId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "catId", column = @Column(name = "catId", nullable = false)),
			@AttributeOverride(name = "branchId", column = @Column(name = "branchId", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "userId", nullable = false)) })
	public ReservationId getId() {
		return this.id;
	}

	public void setId(ReservationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catId", nullable = false, insertable = false, updatable = false)
	public Catalog getTblCatalog() {
		return this.catalog;
	}

	public void setTblCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false, insertable = false, updatable = false)
	public User getTblUser() {
		return this.user;
	}

	public void setTblUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchId", nullable = false, insertable = false, updatable = false)
	public LibraryBranch getTblLibraryBranch() {
		return this.libraryBranch;
	}

	public void setTblLibraryBranch(LibraryBranch libraryBranch) {
		this.libraryBranch = libraryBranch;
	}

	@Column(name = "orderId", unique = true, nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

}
