package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblTransfersId generated by hbm2java
 */
@Embeddable
public class TransfersId implements java.io.Serializable {

	private int fromBranchId;
	private int toBranchId;
	private int catId;

	public TransfersId() {
	}

	public TransfersId(int fromBranchId, int toBranchId, int catId) {
		this.fromBranchId = fromBranchId;
		this.toBranchId = toBranchId;
		this.catId = catId;
	}

	@Column(name = "fromBranchId", nullable = false)
	public int getFromBranchId() {
		return this.fromBranchId;
	}

	public void setFromBranchId(int fromBranchId) {
		this.fromBranchId = fromBranchId;
	}

	@Column(name = "toBranchId", nullable = false)
	public int getToBranchId() {
		return this.toBranchId;
	}

	public void setToBranchId(int toBranchId) {
		this.toBranchId = toBranchId;
	}

	@Column(name = "catId", nullable = false)
	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransfersId))
			return false;
		TransfersId castOther = (TransfersId) other;

		return (this.getFromBranchId() == castOther.getFromBranchId())
				&& (this.getToBranchId() == castOther.getToBranchId())
				&& (this.getCatId() == castOther.getCatId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFromBranchId();
		result = 37 * result + this.getToBranchId();
		result = 37 * result + this.getCatId();
		return result;
	}

}
