package com.gcit.lms.entities;

// Generated Feb 5, 2014 3:10:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name = "tbl_user", catalog = "library", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class User implements java.io.Serializable {

	private int userId;
	private String name;
	private String address;
	private String email;
	private String role;
	private Logins logins;
	private Librarian librarian;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public User() {
	}

	public User(int userId, String name, String address, String role) {
		this.userId = userId;
		this.name = name;
		this.address = address;
		this.role = role;
	}

	public User(int userId, String name, String address, String email,
			String role, Logins logins, Librarian librarian,
			Set<Reservation> reservations) {
		this.userId = userId;
		this.name = name;
		this.address = address;
		this.email = email;
		this.role = role;
		this.logins = logins;
		this.librarian = librarian;
		this.reservations = reservations;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", unique = true, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "role", nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tblUser")
	public Logins getTblLogins() {
		return this.logins;
	}

	public void setTblLogins(Logins logins) {
		this.logins = logins;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "tblUser")
	public Librarian getTblLibrarian() {
		return this.librarian;
	}

	public void setTblLibrarian(Librarian librarian) {
		this.librarian = librarian;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUser")
	public Set<Reservation> getTblReservations() {
		return this.reservations;
	}

	public void setTblReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
